apiVersion: v1
kind: Endpoints
metadata:
  labels:
    app.kubernetes.io/name: prometheus
  name: prometheus
  namespace: gemcloud-monitoring-system
subsets:
- addresses:
  - ip: {{ core_plugins.monitoring.operator.prometheus.external_host.split(":")[0] | lower }}
  ports:
  - port: {{ core_plugins.monitoring.operator.prometheus.external_host.split(":")[1] | int }}
    protocol: TCP