apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: gemcloud-monitoring-system
  labels:
    app.kubernetes.io/name: prometheus
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
      app.kubernetes.io/name: prometheus