apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: alertmanager
  namespace: gemcloud-monitoring-system
  labels:
    app.kubernetes.io/name: alertmanager
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: alertmanager
  namespaceSelector:
    matchNames:
      - gemcloud-monitoring-system
  endpoints:
    - port: http
      path: "/metrics"