apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: gemcloud-monitoring-system
  labels:
    app.kubernetes.io/name: alertmanager
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9093
      targetPort: 9093
  selector:
    app.kubernetes.io/name: alertmanager