#jinja2:lstrip_blocks: True
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: argocd-redis
    app.kubernetes.io/part-of: argocd
  name: argocd-redis
  namespace: gemcloud-workflow-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-redis
      app.kubernetes.io/part-of: argocd
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-redis
        app.kubernetes.io/part-of: argocd
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: argocd-redis
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - command:
        - redis-server
        args:
        - --save
        - ""
        - --appendonly
        - "no"
        image: "{{ global.repository | default('docker.io/kubegems') }}/redis:6.0.10"
        imagePullPolicy: IfNotPresent
        name: redis
        ports:
        - containerPort: 6379
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      {% if global.imagepullsecret is defined %}
      imagePullSecrets:
        - name: {{ global.imagepullsecret | default('kubegems') }}
      {% endif %}