apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: gems-chartmuseum
  name: gems-chartmuseum
  namespace: gemcloud-system
spec:
  ports:
  - name: http-8030
    port: 8030
    protocol: TCP
    targetPort: 8030
  selector:
    app.kubernetes.io/name: gems-chartmuseum
  type: ClusterIP