apiVersion: v1
kind: Endpoints
metadata:
  labels:
    app.kubernetes.io/name: loki
  name: loki-gateway
  namespace: gemcloud-logging-system
subsets:
- addresses:
  - ip: {{ core_plugins.loki.status.host.split(":")[0] | lower }}
  ports:
  - port: {{ core_plugins.loki.status.host.split(":")[1] | int }}
    protocol: TCP