apiVersion: v1
kind: Service
metadata:
  name: loki-gateway
  namespace: gemcloud-logging-system
  labels:
    app.kubernetes.io/name: loki
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3100
      targetPort: 3100
      protocol: TCP
  selector:
      app.kubernetes.io/name: loki