apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: gems-mysql
  name: gems-mysql
  namespace: gemcloud-system
spec:
  ports:
  - name: tcp-3306
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app.kubernetes.io/name: gems-mysql
  type: ClusterIP