apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: gems-eventer
  name: gems-eventer-cfg
  namespace: gemcloud-logging-system
data:
  config.yaml: |
    logLevel: error
    logFormat: json
    route:
      routes:
        - match:
            - receiver: "dump"
    receivers:
      - name: "dump"
        file:
          path: "/dev/stdout"
