apiVersion: v1
kind: Service
metadata:
  name: loki-redis
  namespace: gemcloud-logging-system
  labels:
    app.kubernetes.io/name: loki-redis
spec:
  type: ClusterIP
  ports:
    - name: tcp-6379
      port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app.kubernetes.io/name: loki-redis