#jinja2:lstrip_blocks: True
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: gems-minio
  name: gems-minio
  namespace: gemcloud-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gems-minio
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gems-minio
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: gems-minio
                namespaces:
                  - gemcloud-system
                topologyKey: kubernetes.io/hostname
              weight: 1
      initContainers:
      - image: "{{ global.repository | default('docker.io/kubgems')}}/busybox:latest"
        imagePullPolicy: IfNotPresent
        name: minio-buckets-init-helm
        command: ["mkdir", "-p", "/data/helm"]
        volumeMounts:
        - mountPath: /data
          name: data
      - image: "{{ global.repository | default('docker.io/kubgems')}}/busybox:latest"
        imagePullPolicy: IfNotPresent
        name: minio-buckets-init-logs
        command: ["mkdir", "-p", "/data/logs"]
        volumeMounts:
        - mountPath: /data
          name: data
      containers:
      - env:
        - name: BITNAMI_DEBUG
          value: 'false'
        - name: MINIO_SCHEME
          value: http
        - name: MINIO_FORCE_NEW_KEYS
          value: 'no'
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: access-key
              name: gems-minio
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: secret-key
              name: gems-minio
        - name: MINIO_BROWSER
          value: 'on'
        - name: MINIO_PROMETHEUS_AUTH_TYPE
          value: public
        image: "{{ global.repository | default('docker.io/kubegems') }}/minio:2021.6.17-debian-10-r0"
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /minio/health/live
            port: minio
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        name: minio
        ports:
          - containerPort: 9000
            name: minio
            protocol: TCP
        readinessProbe:
          failureThreshold: 5
          initialDelaySeconds: 5
          periodSeconds: 30
          successThreshold: 1
          tcpSocket:
            port: minio
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 256Mi
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
        volumeMounts:
          - mountPath: /data
            name: data
      dnsPolicy: ClusterFirst
      {% if global.imagepullsecret is defined %}
      imagePullSecrets:
      - name: {{ global.imagepullsecret | default('kubegems')}}
      {% endif %}
      restartPolicy: Always
      securityContext:
        fsGroup: 1001
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: gems-minio-data