apiVersion: v1
kind: ConfigMap
metadata:
  name: gems-log-agent-input
  namespace: gemcloud-logging-system
  labels:
    kubegems.io/plugins: logging
    app.kubernetes.io/name: fluentd
data:
  containerlogs.conf: |
    <source>
      @type tail
      @id input.containers.out
      path /var/log/containers/*.log
      exclude_path /var/log/containers/*gems-log-agent*.log,/var/log/containers/loki*.log,/var/log/containers/*gemcloud-monitoring-system*.log,/var/log/containers/*gemcloud-workflow-system*.log,/var/log/containers/*gemcloud-system*.log
      pos_file /var/log/gems-container.log.pos
      read_from_head true
      #https://docs.fluentd.org/input/tail#in_tail-is-sometimes-stopped-when-monitor-lots-of-files-how-to-avoid-it
      enable_stat_watcher false
      tag kubernetes.*
      <parse>
        @type json
        time_key time
        time_format %Y-%m-%dT%H:%M:%S.%NZ
        utc true
      </parse>
    </source>