kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gems-jaeger-operator
subjects:
- kind: ServiceAccount
  name: jaeger-operator
  namespace: "observability" # change to point to the namespace you installed your operator
roleRef:
  kind: ClusterRole
  name: gems-jaeger-operator
  apiGroup: rbac.authorization.k8s.io