#jinja2:lstrip_blocks: True
apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: gemcloud
  namespace: gemcloud-monitoring-system
  labels:
    app.kubernetes.io/name: grafana
spec:
  baseImage: "{{ global.repository | default('docker.io/kubegems')}}/grafana:{{ kubernetes_plugins.grafana.details.version | default('latest') }}"
  client:
    timeout: 5
    preferService: true
  service:
    labels:
      app.kubernetes.io/name: grafana
    type: NodePort
  deployment:
    skipCreateAdminAccount: true
    envFrom:
      - secretRef:
          name: external-credentials
    labels:
      app.kubernetes.io/name: grafana
    replicas: 1
    securityContext:
      runAsUser: 1001
      fsGroup: 1001
      runAsNonRoot: true
      runAsGroup: 1001
    containerSecurityContext:
      runAsUser: 1001
      runAsGroup: 1001
      fsGroup: 1001
      allowPrivilegeEscalation: false
    affinity:
      podAffinity:

      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: grafana
              namespaces:
                - "gemcloud-monitoring-system"
              topologyKey: kubernetes.io/hostname
            weight: 1
      nodeAffinity:

    livenessProbeSpec:
      initialDelaySeconds: 120
      periodSeconds: 10
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 6
    readinessProbeSpec:
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 6
  resources:
    limits: 
      cpu: 1
      memory: 512Mi
    requests: 
      cpu: 200m
      memory: 128Mi
#  dataStorage:
#    accessModes:
#    - ReadWriteOnce
#    size: 20Gi
#    storageClassName: local-path
  ingress:
    enabled: false
    hostname: grafana.local
    tlsEnabled: false
    tlsSecretName: grafana.local-tls
    path: /
  config:
    auth.anonymous:
      enabled: True
    alerting:
      enabled: false
    analytics:
      check_for_updates: false
      reporting_enabled: false
    log:
      level: warn
      mode: console
    security:
      disable_gravatar: false
      disable_initial_admin_creation: false
    server:
      root_url: |-
        http://grafana.gemcloud-monitoring-system.svc.cluster.local:3000
  dashboardLabelSelector:
    - matchExpressions:
        - { key: app, operator: In, values: [ grafana ] }