#jinja2:lstrip_blocks: True
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path
  annotations:
    storageclass.kubegems.io/supported-access-modes: rwo
    {% if kubernetes_plugins.local_path.default_class | default(false) | bool %}
    storageclass.kubernetes.io/is-default-class: 'true'
    {% endif %}
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete