apiVersion: v1
data:
  redis-server.conf: |-
    requirepass gems-redis-password
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: gems-redis
  name: gems-redis-config
  namespace: gemcloud-system