apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: gems-redis
  name: gems-redis
  namespace: gemcloud-system
spec:
  ports:
  - name: tcp-redis
    port: 6379
    protocol: TCP
    targetPort: redis
  selector:
    app.kubernetes.io/name: gems-redis
  type: ClusterIP