apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: gems-controller-manager
    control-plane: controller-manager
  name: gems-leader-election-rolebinding
  namespace: gemcloud-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gems-leader-election-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: gemcloud-system
