apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: gems-controller-manager
    control-plane: controller-manager
  name: gems-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
