apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nginx-ingress-operator-leader-election-rolebinding
  namespace: gemcloud-gateway-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nginx-ingress-operator-leader-election-role
subjects:
  - kind: ServiceAccount
    name: nginx-ingress-operator-controller-manager
    namespace: gemcloud-gateway-system
