apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: loki
  namespace: gemcloud-monitoring-system
spec:
  name: loki-ds.yaml
  datasources:
    - name: Loki
      type: loki
      access: proxy
      url: "http://loki-gateway.gemcloud-logging-system.svc.cluster.local:3100"
      isDefault: false
      version: 1
      editable: false
      jsonData:
        maxLines: 2000
        tlsSkipVerify: true
        timeInterval: "5s"