apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: prometheus
  namespace: gemcloud-monitoring-system
spec:
  name: prometheus-ds.yaml
  datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: "http://prometheus.gemcloud-monitoring-system.svc.cluster.local:9090"
      isDefault: true
      version: 1
      editable: false
      jsonData:
        tlsSkipVerify: true
        timeInterval: "5s"