kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gems-prometheus-psp
  labels:
    app.kubernetes.io/name: prometheus
rules:
  - apiGroups: ['extensions']
    resources: ['podsecuritypolicies']
    verbs: ['use']
    resourceNames:
      - prometheus