apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gems-agent
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - list
  - get
  - watch
  - patch
  - create
  - update
  - delete
- nonResourceURLs:
  - '*'
  verbs:
  - list
  - get
  - watch
  - patch
  - create
  - update
  - delete
