apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gems-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gems-agent
subjects:
- kind: ServiceAccount
  name: gems-agent
  namespace: gemcloud-system
