#jinja2:lstrip_blocks: True
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gems-agent
  namespace: gemcloud-system
  labels:
    app.kubernetes.io/name: gems-agent
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gems-agent
  replicas: {{ core_plugins.kubegems_local.operator.gems_agent.replicas | default('1') }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gems-agent
    spec:
      serviceAccount: gems-agent
      {% if global.imagepullsecret is defined %}
      imagePullSecrets:
        - name: {{ golobal.imagepullsecret | default('kubegems')}}
      {% endif %}
      containers:
        - name: gems-agent
          image: "{{ global.repository | default('docker.io')}}/kubegems:{{ core_plugins.kubegems_local.details.version | default('latest') }}"
          imagePullPolicy: IfNotPresent
          args: ["agent"]
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DEBUGOPTIONS-MYCONTAINER
              value: "gems-agent-kubectl"
            - name: "DEBUG"
              {% if core_plugins.kubegems_local.operator.gems_agent.debug is defined and core_plugins.kubegems_local.operator.gems_agent.debug %}
              value: "true"
              {% else %}
              value: "false"
              {% endif %}
            - name: "LOGLEVEL"
              value: "info"
            - name: "EXPORTER_LISTEN"
              value: ":9100"
            - name: "EXPORTER_METRICPATH"
              value: "/metrics"
            - name: "EXPORTER_INCLUDEEXPORTERMETRICS"
              value: "false"
            - name: "EXPORTER_MAXREQUESTS"
              value: "40"
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 1000m
              memory: 2Gi
          livenessProbe:
            tcpSocket:
              port: 8041
          ports:
            - containerPort: 8040
              name: https-8040
            - containerPort: 8041
              name: http-8041
            - containerPort: 9100
              name: http-9100
          volumeMounts:
            - name: cert
              mountPath: /serv/certs
            - mountPath: /etc/localtime
              name: timezone
      volumes:
        - hostPath:
            path: /etc/localtime
          name: timezone
        - name: cert
          secret:
            secretName: gems-agent-cert
