apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: node-problem-detector
  name: node-problem-detector
  namespace: kube-system
spec:
  clusterIP: None
  type: ClusterIP
  ports:
    - name: metrics
      port: 20258
      targetPort: 20258
      protocol: TCP
  selector:
    app.kubernetes.io/name: node-problem-detector