#jinja2:lstrip_blocks: True
apiVersion: v1
kind: ConfigMap
metadata:
  name: node-local-dns
  namespace: kube-system
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
data:
  Corefile: |
    cluster.local:53 {
        errors
        cache {
                success 9984 30
                denial 9984 5
        }
        reload
        loop
        bind 169.254.20.10
        forward . {{ kubernetes_plugins.node_local_dns.operator.dns_upsteam | default('10.96.0.10') }} {
                force_tcp
        }
        prometheus :9253
        health 169.254.20.10:8080
        }
    in-addr.arpa:53 {
        errors
        cache 30
        reload
        loop
        bind 169.254.20.10
        forward . {{ kubernetes_plugins.node_local_dns.operator.dns_upsteam | default('10.96.0.10') }} {
                force_tcp
        }
        prometheus :9253
        }
    ip6.arpa:53 {
        errors
        cache 30
        reload
        loop
        bind 169.254.20.10
        forward . {{ kubernetes_plugins.node_local_dns.operator.dns_upsteam | default('10.96.0.10') }} {
                force_tcp
        }
        prometheus :9253
        }
    .:53 {
        errors
        cache 30
        reload
        loop
        bind 169.254.20.10
        forward . {{ kubernetes_plugins.node_local_dns.operator.dns_upsteam | default('10.96.0.10') }} {
                force_tcp
        }
        prometheus :9253
        }