kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gems-node-exporter-psp
  labels:
    app.kubernetes.io/name: node-exporter
rules:
  - apiGroups: ['extensions']
    resources: ['podsecuritypolicies']
    verbs: ['use']
    resourceNames:
      - node-exporter