apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gems-prometheus-operator
  labels:
    app.kubernetes.io/name: prometheus-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gems-prometheus-operator
subjects:
  - kind: ServiceAccount
    name: prometheus-operator
    namespace: gemcloud-monitoring-system