apiVersion: v1
kind: Service
metadata:
  name: prometheus-operator
  namespace: gemcloud-monitoring-system
  labels:
    app.kubernetes.io/name: prometheus-operator
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
  selector:
    app.kubernetes.io/name: prometheus-operator