#jinja2:lstrip_blocks: True
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging-operator
  namespace: gemcloud-logging-system
  labels:
    app.kubernetes.io/name: logging-operator
    app.kubernetes.io/version: "3.15.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: logging-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: logging-operator
    spec:
      {% if global.imagepullsecret is defined %}
      imagePullSecrets:
      - name: {{ global.imagepullsecret | default('kubegems')}}
      {% endif %}
      containers:
        - name: logging-operator
          image: "{{ global.repository | default('docker.io/kubegems')}}/logging-operator:{{ core_plugins.logging.details.version | default('v3.15.0')}}"
          args:
            - -enable-leader-election=true
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          ports:
            - name: http
              containerPort: 8080
      serviceAccountName: logging-operator