apiVersion: v1
kind: Service
metadata:
  name: logging-operator
  namespace: gemcloud-logging-system
  labels:
    app.kubernetes.io/name: logging-operator
    app.kubernetes.io/version: "3.15.0"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: logging-operator