apiVersion: v1
kind: Service
metadata:
  name: prometheus-kube-controller-manager
  namespace: kube-system
  labels:
    kubegems.io/plugins: monitoring
    app.kubernetes.io/name: kube-controller-manager
spec:
  selector:
    component: kube-controller-manager
  ports:
    - name: https-metrics
      port: 10257
      protocol: TCP
      targetPort: 10257
  type: ClusterIP
