apiVersion: v1
kind: Service
metadata:
  name: prometheus-kube-proxy
  namespace: kube-system
  labels:
    kubegems.io/plugins: monitoring
    app.kubernetes.io/name: kube-proxy
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 10249
      protocol: TCP
      targetPort: 10249
  selector:
    k8s-app: kube-proxy
  type: ClusterIP