#jinja2:lstrip_blocks: True
apiVersion: v1
kind: Secret
metadata:
  name: gems-secret
  namespace: gemcloud-system
  labels:
    app.kubernetes.io/name: gems-service
type: Opaque
data:
  argo-admin-password: Q2xvdWRtaW5kczE2ODg=
  mysql-root-password: "{{ lookup('password', '/dev/null length=12 chars=ascii_letters') | b64encode }}"
  redis-password: "{{ lookup('password', '/dev/null length=12 chars=ascii_letters') | b64encode }}"
  gitea-root-user: cm9vdA==
  gitea-root-password: "{{ lookup('password', '/dev/null length=12 chars=ascii_letters') | b64encode }}"