apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: grafana-operator
  name: gems-grafana-operator
rules:
  - apiGroups:
      - integreatly.org
    resources:
      - grafanadashboards
      - grafanadashboards/status
    verbs: ['get', 'list', 'update', 'watch']
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs: ['get', 'list', 'watch']
  - apiGroups:
      - ""
    resources:
      - events
    verbs: ['create', 'patch']