apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: grafana-operator
  name: grafana-operator
  namespace: gemcloud-monitoring-system
  labels:
    app.kubernetes.io/name: grafana-operator
    app.kubernetes.io/component: operator
roleRef:
  name: grafana-operator
  kind: Role
  apiGroup: ""
subjects:
  - kind: ServiceAccount
    name: grafana-operator