kind: Secret
apiVersion: v1
metadata:
  labels:
    app.kubernetes.io/name: grafana-operator
  name: external-credentials
  namespace: gemcloud-monitoring-system
stringData:
  GF_SECURITY_ADMIN_PASSWORD: 1qaz@WSX3edc
  GF_SECURITY_ADMIN_USER: admin
type: Opaque
