# ref. https://github.com/istio/istio/blob/master/samples/addons/extras/prometheus-operator.yaml 有增删
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istio-component-monitor
  namespace: istio-system
  labels:
    monitoring: istio-components
    release: istio
spec:
  jobLabel: istio
  targetLabels: [app]
  selector:
    matchExpressions:
      - { key: istio, operator: In, values: [pilot] }
  namespaceSelector:
    matchNames:
      - istio-system
  endpoints:
    - path: /metrics
      port: http-monitoring
      honorLabels: true
      relabelings:
        - regex: endpoint|service|container|pod|namespace
          action: labeldrop
