#jinja2:lstrip_blocks: True
apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: cainjector
        app.kubernetes.io/component: cainjector
        app.kubernetes.io/instance: cert-manager
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: cainjector
        helm.sh/chart: cert-manager-v1.4.0
    name: cert-manager-cainjector
    namespace: cert-manager
spec:
    replicas: 1
    selector:
        matchLabels:
            app.kubernetes.io/component: cainjector
            app.kubernetes.io/instance: cert-manager
            app.kubernetes.io/name: cainjector
    template:
        metadata:
            labels:
                app: cainjector
                app.kubernetes.io/component: cainjector
                app.kubernetes.io/instance: cert-manager
                app.kubernetes.io/managed-by: Helm
                app.kubernetes.io/name: cainjector
                helm.sh/chart: cert-manager-v1.4.0
        spec:
            containers:
                - args:
                    - --v=2
                    - --leader-election-namespace=kube-system
                  env:
                    - name: POD_NAMESPACE
                      valueFrom:
                        fieldRef:
                            fieldPath: metadata.namespace
                  image: "{{ global.repository | default('docker.io/kubegems')}}/cert-manager-cainjector:{{ core_plugins.cert_manager.details.version |default('v1.4.0') }}"
                  imagePullPolicy: IfNotPresent
                  name: cert-manager
                  resources: {}
            securityContext:
                runAsNonRoot: true
            serviceAccountName: cert-manager-cainjector
            {% if global.imagepullsecret is defined %}
            imagePullSecrets:
              - name: {{ global.imagepullsecret | default('kubegems')}}
            {% endif %}