name: Create Cluster

on:
  push:
    branches:
      - 'main'
      - 'release-*'
    # Publish semver tags as releases.
    tags: ["v*.*.*"]
  pull_request:
    branches:
      - 'main'
      - 'release-*'

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0
        kubectl_version: v1.20.8
        cluster_name: kubegems-installer-test

