apiVersion: v1
kind: Secret
metadata:
  name: gems-gitea
  namespace: gemcloud-system
  labels:
    app.kubernetes.io/name: gems-gitea
type: Opaque
stringData:
  app.ini: |-
    [database]
    DB_TYPE = sqlite3

    [metrics]
    ENABLED = false

    [repository]
    ROOT = /data/git/gitea-repositories

    [security]
    INSTALL_LOCK = true

    [server]
    APP_DATA_PATH = /data
    DOMAIN = gemcloud-system.svc.cluster.local
    ENABLE_PPROF = false
    HTTP_PORT = 3000
    PROTOCOL = http
    ROOT_URL = http://gems-gitea.gemcloud-system:3000/
    SSH_DOMAIN = gems-gitea
    SSH_LISTEN_PORT = 22
    SSH_PORT = 22