apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: gems-gitea
  name: gems-gitea
  namespace: gemcloud-system
spec:
  ports:
  - name: tcp-3000
    port: 3000
    protocol: TCP
    targetPort: 3000
  - name: tcp-22
    port: 22
    protocol: TCP
    targetPort: 22
  selector:
    app.kubernetes.io/name: gems-gitea
  type: ClusterIP