apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gems-kube-state-metrics-psp
  labels:
    app.kubernetes.io/name: kube-state-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gems-kube-state-metrics-psp
subjects:
  - kind: ServiceAccount
    name: kube-state-metrics
    namespace: gemcloud-monitoring-system