kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gems-kube-state-metrics-psp
  labels:
    app.kubernetes.io/name: kube-state-metrics
rules:
  - apiGroups: ['extensions']
    resources: ['podsecuritypolicies']
    verbs: ['use']
    resourceNames:
      - kube-state-metrics