apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics
  namespace: gemcloud-monitoring-system
  annotations:
  labels:
    app.kubernetes.io/name: kube-state-metrics
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      nodePort: null
  selector:
    app.kubernetes.io/name: kube-state-metrics